screen:
  width: 800
  height: 600

squirrel:
  size:
    width: 50
    height: 50

acorn:
  size:
    width: 30
    height: 30

obstacle:
  size:
    width: 40
    height: 40

initial_speed: 5
level_up_threshold: 10
